MAX_LENGTH_FIELD_RECIPE_MODELS = 200
MAX_LENGTH_EMAILFIELD = 254
MAX_LENGTH_FIELD_USER_MODELS = 150

MIN_TIME_COOK = MIN_INGREDIENT_VALUE = 1
MAX_TIME_COOK = 4320
MAX_INGREDIENT_VALUE = 32000

PAGE_SIZE = 6
MAX_PAGE_SIZE = 50
