# Generated by Django 3.2.3 on 2023-09-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230905_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'ordering': ('recipe',), 'verbose_name': 'ингредиент рецепта', 'verbose_name_plural': 'ингредиенты рецепта'},
        ),
        migrations.AlterModelOptions(
            name='tagrecipe',
            options={'ordering': ('tag',), 'verbose_name': 'тег рецепта', 'verbose_name_plural': 'теги рецепта'},
        ),
    ]
