# Generated by Django 3.2.3 on 2023-09-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20230906_1501'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique recipe name',
        ),
    ]
